services:
  caddy:
    image: 'ghcr.io/caddybuilds/caddy-cloudflare:latest'
    network_mode: host
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'   
    volumes:
      - '/conf/Caddyfile:/etc/caddy/Caddyfile'
      - 'caddy_data:/data'
      - 'caddy_config:/config'
    environment:
      - 'CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}'
    restart: always

volumes:
  caddy_data:
  caddy_config:
